ARG sourceimage=stash86/freqtrade
ARG sourcetag=latest
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-freqai.txt /freqtrade/

RUN pip install --upgrade pip
RUN pip install -r requirements-freqai.txt --user --no-cache-dir

