ARG sourceimage=stash86/freqtrade
ARG sourcetag=linux-arm64-v8
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-freqai.txt requirements-freqai-rl.txt /freqtrade/

RUN pip install -r requirements-freqai-rl.txt --user --no-cache-dir
